const usersData = [
  {
    id: 1,
    name: "Aarav Sharma",
    role: "Frontend Developer",
    email: "aarav.sharma@example.com",
    location: "Bangalore",
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: 2,
    name: "Priya Verma",
    role: "UI/UX Designer",
    email: "priya.verma@example.com",
    location: "Delhi",
    avatar: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: 3,
    name: "Rohit Mehta",
    role: "Backend Developer",
    email: "rohit.mehta@example.com",
    location: "Mumbai",
    avatar: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: 4,
    name: "Sneha Kapoor",
    role: "Product Manager",
    email: "sneha.kapoor@example.com",
    location: "Pune",
    avatar: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: 5,
    name: "Kunal Singh",
    role: "Full Stack Developer",
    email: "kunal.singh@example.com",
    location: "Noida",
    avatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 6,
    name: "Ananya Gupta",
    role: "Data Analyst",
    email: "ananya.gupta@example.com",
    location: "Gurgaon",
    avatar: "https://i.pravatar.cc/150?img=6",
  },
  {
    id: 7,
    name: "Vikram Joshi",
    role: "DevOps Engineer",
    email: "vikram.joshi@example.com",
    location: "Hyderabad",
    avatar: "https://i.pravatar.cc/150?img=7",
  },
  {
    id: 8,
    name: "Neha Malhotra",
    role: "HR Manager",
    email: "neha.malhotra@example.com",
    location: "Chandigarh",
    avatar: "https://i.pravatar.cc/150?img=8",
  },
  {
    id: 9,
    name: "Arjun Patel",
    role: "Mobile App Developer",
    email: "arjun.patel@example.com",
    location: "Ahmedabad",
    avatar: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: 10,
    name: "Pooja Nair",
    role: "QA Engineer",
    email: "pooja.nair@example.com",
    location: "Kochi",
    avatar: "https://i.pravatar.cc/150?img=10",
  },
  {
    id: 11,
    name: "Siddharth Rao",
    role: "Cloud Architect",
    email: "siddharth.rao@example.com",
    location: "Bangalore",
    avatar: "https://i.pravatar.cc/150?img=11",
  },
  {
    id: 12,
    name: "Riya Chatterjee",
    role: "Content Strategist",
    email: "riya.chatterjee@example.com",
    location: "Kolkata",
    avatar: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: 13,
    name: "Amit Kulkarni",
    role: "Business Analyst",
    email: "amit.kulkarni@example.com",
    location: "Nagpur",
    avatar: "https://i.pravatar.cc/150?img=13",
  },
  {
    id: 14,
    name: "Isha Bansal",
    role: "Marketing Specialist",
    email: "isha.bansal@example.com",
    location: "Jaipur",
    avatar: "https://i.pravatar.cc/150?img=14",
  },
  {
    id: 15,
    name: "Manish Yadav",
    role: "Sales Manager",
    email: "manish.yadav@example.com",
    location: "Lucknow",
    avatar: "https://i.pravatar.cc/150?img=15",
  },
  {
    id: 16,
    name: "Kavya Iyer",
    role: "Technical Writer",
    email: "kavya.iyer@example.com",
    location: "Chennai",
    avatar: "https://i.pravatar.cc/150?img=16",
  },
  {
    id: 17,
    name: "Rahul Khanna",
    role: "Cyber Security Analyst",
    email: "rahul.khanna@example.com",
    location: "Indore",
    avatar: "https://i.pravatar.cc/150?img=17",
  },
  {
    id: 18,
    name: "Simran Kaur",
    role: "Recruitment Lead",
    email: "simran.kaur@example.com",
    location: "Amritsar",
    avatar: "https://i.pravatar.cc/150?img=18",
  },
  {
    id: 19,
    name: "Nikhil Saxena",
    role: "AI Engineer",
    email: "nikhil.saxena@example.com",
    location: "Bhopal",
    avatar: "https://i.pravatar.cc/150?img=19",
  },
  {
    id: 20,
    name: "Tanya Roy",
    role: "Operations Manager",
    email: "tanya.roy@example.com",
    location: "Ranchi",
    avatar: "https://i.pravatar.cc/150?img=20",
  },
];

export default usersData;
