const CardData = [
  {
    id: 1,
    title: "Learn HTML Basics",
    description: "Understand tags, elements, and document structure",
    status: "Completed",
    category: "Frontend",
    author: "Vivek",
    priority: "Low",
    date: "2026-01-01",
  },
  {
    id: 2,
    title: "Learn CSS Flexbox",
    description: "Build responsive layouts using flexbox",
    status: "Completed",
    category: "Frontend",
    author: "Vivek",
    priority: "Medium",
    date: "2026-01-02",
  },
  {
    id: 3,
    title: "Learn CSS Grid",
    description: "Create complex layouts using CSS Grid",
    status: "In Progress",
    category: "Frontend",
    author: "Vivek",
    priority: "Medium",
    date: "2026-01-03",
  },
  {
    id: 4,
    title: "JavaScript Basics",
    description: "Variables, functions, loops, and conditions",
    status: "Completed",
    category: "JavaScript",
    author: "Vivek",
    priority: "High",
    date: "2026-01-04",
  },
  {
    id: 5,
    title: "JavaScript ES6",
    description: "Learn arrow functions, destructuring, and modules",
    status: "In Progress",
    category: "JavaScript",
    author: "Vivek",
    priority: "High",
    date: "2026-01-05",
  },
  {
    id: 6,
    title: "React Fundamentals",
    description: "Components, props, and JSX",
    status: "Completed",
    category: "React",
    author: "Vivek",
    priority: "High",
    date: "2026-01-06",
  },
  {
    id: 7,
    title: "React State & Props",
    description: "Manage data flow between components",
    status: "Completed",
    category: "React",
    author: "Vivek",
    priority: "High",
    date: "2026-01-07",
  },
  {
    id: 8,
    title: "React Hooks",
    description: "Learn useState and useEffect",
    status: "In Progress",
    category: "React",
    author: "Vivek",
    priority: "High",
    date: "2026-01-08",
  },
  {
    id: 9,
    title: "React Forms",
    description: "Controlled and uncontrolled components",
    status: "Pending",
    category: "React",
    author: "Vivek",
    priority: "Medium",
    date: "2026-01-09",
  },
  {
    id: 10,
    title: "React Lists & Keys",
    description: "Rendering lists efficiently",
    status: "Completed",
    category: "React",
    author: "Vivek",
    priority: "Medium",
    date: "2026-01-10",
  },
  {
    id: 11,
    title: "Git Basics",
    description: "Version control fundamentals",
    status: "Completed",
    category: "Git",
    author: "Vivek",
    priority: "Low",
    date: "2026-01-11",
  },
  {
    id: 12,
    title: "Git Branching",
    description: "Work with multiple branches",
    status: "In Progress",
    category: "Git",
    author: "Vivek",
    priority: "Medium",
    date: "2026-01-12",
  },
  {
    id: 13,
    title: "GitHub Workflow",
    description: "Pull requests and code reviews",
    status: "Pending",
    category: "Git",
    author: "Vivek",
    priority: "Medium",
    date: "2026-01-13",
  },
  {
    id: 14,
    title: "Node.js Basics",
    description: "Understand runtime and modules",
    status: "Pending",
    category: "Backend",
    author: "Vivek",
    priority: "High",
    date: "2026-01-14",
  },
  {
    id: 15,
    title: "Express.js Basics",
    description: "Build REST APIs with Express",
    status: "Pending",
    category: "Backend",
    author: "Vivek",
    priority: "High",
    date: "2026-01-15",
  },
  {
    id: 16,
    title: "API Integration",
    description: "Consume APIs in React using fetch",
    status: "In Progress",
    category: "React",
    author: "Vivek",
    priority: "High",
    date: "2026-01-16",
  },
  {
    id: 17,
    title: "Search Functionality",
    description: "Implement search and filter logic",
    status: "Pending",
    category: "React",
    author: "Vivek",
    priority: "Medium",
    date: "2026-01-17",
  },
  {
    id: 18,
    title: "Pagination",
    description: "Handle large datasets efficiently",
    status: "Pending",
    category: "React",
    author: "Vivek",
    priority: "Medium",
    date: "2026-01-18",
  },
  {
    id: 19,
    title: "Performance Optimization",
    description: "Improve React app performance",
    status: "Pending",
    category: "Advanced",
    author: "Vivek",
    priority: "High",
    date: "2026-01-19",
  },
  {
    id: 20,
    title: "Deploy React App",
    description: "Deploy application to production",
    status: "Pending",
    category: "DevOps",
    author: "Vivek",
    priority: "High",
    date: "2026-01-20",
  },
];

export default CardData;
